include_guard()

hunter_config(brotli
	URL "https://github.com/Telefrag-Software/brotli/archive/refs/heads/hunter-1.2.0.1.zip"
	VERSION "1.2.0.1"
	SHA1 "77118cfb19c5fa3267d13f680dc7d45c5ff51e82"
	CMAKE_ARGS
		BUILD_SHARED_LIBS=OFF
		BROTLI_BUILD_TOOLS=OFF
		BROTLI_DISABLE_TESTS=ON
		ENABLE_COVERAGE=OFF
)

hunter_config(c-ares
	URL "https://codeload.github.com/c-ares/c-ares/zip/tags/v1.34.6"
	VERSION "1.34.6"
	SHA1 "2470860765112049c3aba8a79b76f438ae73b1ba"
	CMAKE_ARGS
		CARES_STATIC=ON
		CARES_SHARED=OFF
		CARES_INSTALL=ON
		CARES_STATIC_PIC=OFF
		CARES_BUILD_TESTS=OFF
		CARES_BUILD_CONTAINER_TESTS=OFF
		CARES_BUILD_TOOLS=OFF
		CARES_SYMBOL_HIDING=ON
		CARES_THREADS=ON
		CARES_COVERAGE=OFF
)

hunter_config(Libssh2
	URL "https://codeload.github.com/libssh2/libssh2/zip/tags/libssh2-1.11.1"
	VERSION "1.11.1"
	SHA1 "9ce8506fed4742280730b15c7d9b64d0daef3955"
	CMAKE_ARGS
		BUILD_STATIC_LIBS=ON
		BUILD_SHARED_LIBS=OFF
		LIBSSH2_DISABLE_INSTALL=OFF
		BUILD_EXAMPLES=OFF
		BUILD_TESTING=OFF
		BUILD_OSSFUZZ=OFF
		HIDE_SYMBOLS=ON
		LIBSSH2_NO_DEPRECATED=OFF
		LIBSSH2_CLANG_TIDY=OFF
		ENABLE_ECDSA_WINCNG=OFF
		LINT=OFF
		LIBSSH2_BUILD_DOCS=OFF
)

hunter_config(OpenSSL
	VERSION "3.5.1"
)

hunter_config(ZLIB
	URL "https://github.com/Telefrag-Software/zlib/archive/refs/heads/hunter-1.3.1.2.zip"
	VERSION "1.3.1.2"
	SHA1 "0a8b433ea1eac928a1dfaff3f533dfba61b3aeb9"
	CMAKE_ARGS
		ZLIB_BUILD_TESTING=OFF
		ZLIB_BUILD_SHARED=OFF
		ZLIB_BUILD_STATIC=ON
		ZLIB_BUILD_MINIZIP=OFF
		ZLIB_INSTALL=ON
		ZLIB_PREFIX=OFF
		ZLIB_INSTALL_DOCS=OFF
		ZLIB_INSTALL_LICENSES=OFF
)

hunter_config(zstd
	URL "https://codeload.github.com/facebook/zstd/zip/tags/v1.5.7"
	VERSION "1.5.7.0"
	SHA1 "8bd73c3d2bf87f0c033299f5d05fb4bde2480ad1"
	CMAKE_ARGS
		ZSTD_LEGACY_SUPPORT=OFF
		ZSTD_MULTITHREAD_SUPPORT=ON
		ZSTD_BUILD_PROGRAMS=OFF
		ZSTD_BUILD_CONTRIB=OFF
		ZSTD_PROGRAMS_LINK_SHARED=OFF
		ZSTD_BUILD_TESTS=OFF
		ZSTD_USE_STATIC_RUNTIME=ON
		ZSTD_ENABLE_CXX=ON
)
